// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET6_Calculator_API.Data;

#nullable disable

namespace NET6CalculatorAPI.Migrations
{
    [DbContext(typeof(LoggerContext))]
    [Migration("20221114173114_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("NET6_Calculator_API.Data.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArithmeticOperator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("FirstNumber")
                        .HasColumnType("REAL");

                    b.Property<float?>("Result")
                        .HasColumnType("REAL");

                    b.Property<float>("SecondNumber")
                        .HasColumnType("REAL");

                    b.Property<bool>("SuccessfulResult")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
